#!/bin/sh
#
# Set up environment variables for general build tool to operate
#

if ! [ -f ./buildenv ]; then
	echo "Need to source from the buildenv directory" >&2
	return 0
fi

export ZOPEN_ROOT="${PWD}"
export ZOPEN_TYPE="TARBALL"
export ZOPEN_TARBALL_URL="https://ftp.gnu.org/gnu/sed/sed-4.8.tar.gz"
export ZOPEN_TARBALL_DEPS="curl make gzip autoconf automake gettext makeinfo perl rsync"
